services:
  client:
    build: ./client
    command: npm start
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - node-modules-volume-react:/app/node_modules 
    stdin_open: true
    tty: true

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
     - ./db:/data/db

  # mongo-express service
  mongo-express:
    depends_on:
      - mongo
    command: npm start
    build: ./server
    container_name: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSER: root
      ME_CONFIG_MONGODB_ADMINPASS: password
      ME_CONFIG_MONGODB_SERVER: mongo 

    volumes:
      - ./server:/app
      - node-modules-volume-express:/app/node_modules 
volumes:
  node-modules-volume-react:
  node-modules-volume-express:
  node-modules-volume-mongo:
